{
 "title": "current_voltage",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": {
    "content": "# Railway Signaling Device Health Monitoring\n\nBy current and voltage measurement.\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "History of Alert",
   "type": "alertlist",
   "gridPos": { "h": 10, "w": 8, "x": 12, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current State Alert",
   "type": "alertlist",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "My Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Device Health",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "query": "SELECT last(\"value\") FROM \"temperature\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt", "label": "Volt" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "voltage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Device Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "yaxes": [
    { "format": "%", "label": "Performance" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "performance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "mamp" } },
   "yaxes": [
    { "format": "mamp", "label": "Miliampere" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "current",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}